# -*- coding: utf-8 -*-
"""openinapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gGqAqGc6D5ZiTHk3xAfH3WuDez8_2OSu

Cloning of Git repo
"""

!rm -rf /content/sample_data
!mkdir /content/sample_data

!git clone https://github.com/zabique/Wav2Lip
!git clone https://github.com/anshikaxsingh/Lip_Sync--A-V

"""Loading pretrained model"""

!wget 'https://iiitaphyd-my.sharepoint.com/personal/radrabha_m_research_iiit_ac_in/_layouts/15/download.aspx?share=EdjI7bZlgApMqsVoEUUXpLsBxqXbn5z8VTmoxp55YNDcIA' -O '/content/Wav2Lip/checkpoints/openinapp.pth'
a = !pip install https://raw.githubusercontent.com/AwaleSajil/ghc/master/ghc-1.0-py3-none-any.whl

"""Loading pretrained model for face detection"""

!cd Wav2Lip && pip install -r requirements.txt
#download pretrained model for face detection
!wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "/content/Wav2Lip/checkpoints/facedetect.pth"

!pip install -q youtube-dl
!pip install ffmpeg-python
!pip install librosa==0.9.1

"""Installing required packages"""

from IPython.display import HTML, Audio
from google.colab.output import eval_js
from base64 import b64decode
import numpy as np
from scipy.io.wavfile import read as wav_read
import io
import ffmpeg

from IPython.display import clear_output
clear_output()
print("\nDone")

"""Inferencing using my model (GAN) model"""

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/openinapp.pth --face "/content/WhatsApp Video 2023-10-06 at 13.19.53_10963368.mp4" --audio "/content/output10.wav"

"""Playing the generated video"""

from IPython.display import HTML
from base64 import b64encode
mp4 = open('/content/Wav2Lip/results/result_voice.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f"""
<video width="50%" height="50%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")

"""OTH files -- (link)
.pth files are quite large so I have uploaded them in the drive, follow the pasted link --
https://drive.google.com/drive/folders/1q5uDGIJuVgd5tcS4CJuQie8GGQsDPmm-?usp=sharing

"""